version: '3.8'
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
    ports:
      - 3306:3306
  proxysql:
    image: proxysql/proxysql
    deploy:
      replicas: 3
    ports:
      - 6032:6032
      - 6033:6033
    volumes:
    - ./proxysql.cnf:/etc/proxysql.cnf
    links:
      - mysql
# volumes:
#   logvolume01: {}
